from os.path import join

GAN_CARNIVORO = 100
GAN_HERBIVORO = 900
RANGO_INCUBACION = [1,5]
RECAUDACION_CONSTRUCCION = 500
SEMANAS_MAXIMAS = 10
VISITANTES = [10, 200]
MULTIPLICADOR_RECAUDACION = 3
EVENTO_HERBIVOROS = 1000
EVENTO_CARNIVOROS = 2000
MIN_EX_CARNIVORO = 2
MAX_EX_CARNIVORO = 4
MIN_EX_HERVIBORO = 1
MAX_EX_HERVIBORO = 3
FEROCIDAD = [10, 150]
ADORABILIDAD = [40, 100]
INCREMENTO_FEROCIDAD = 20
INCREMENTO_ADORABILIDAD = 15
PROBABILIDAD_EVENTO = 0.9
N_GRANJAS = 3
N_PASEOS = 3

RUTA_CSV = join("especimenes.csv")
